### ISSUE TITLE
Missing dependency "sherlock"

### ISSUE THREAD

**Issue by luto** [martflu/aurora#591]
```
(py3env) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cp local_settings.example.py local_settings.py
(py3env) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cp Slides/settings.example.py Slides/settings.py
(py3env) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/py3env/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/py3env/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/vagrant/py3env/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/py3env/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/py3env/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/home/vagrant/py3env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/vagrant/PlagCheck/__init__.py", line 5, in <module>
    from .tasks import app as celery_app  # noqa
  File "/vagrant/PlagCheck/tasks.py", line 15, in <module>
    import sherlock
ImportError: No module named 'sherlock'
```

Installing the python module `sherlock` requires the apt-package `libmemcached-dev`. Once both have been installed, the `migrate`-call still fails, to python 2 vs. 3 issues.

```
  File "/vagrant/PlagCheck/__init__.py", line 5, in <module>
    from .tasks import app as celery_app  # noqa
  File "/vagrant/PlagCheck/tasks.py", line 15, in <module>
    import sherlock
  File "/home/vagrant/py3env/lib/python3.4/site-packages/sherlock/__init__.py", line 491, in <module>
    from . import lock
  File "/home/vagrant/py3env/lib/python3.4/site-packages/sherlock/lock.py", line 207
    except LockException, err:
                        ^
SyntaxError: invalid syntax
```

**Comment by SxDx** [comment]
You don't need the Python module Sherlock, you need the C Module Sherlock. The installation Process is outlined here: https://github.com/martflu/aurora/blob/master/PlagCheck/README.md

@flozzone This need better documentation on the main Readme file or an update of the provisioning process to automate the installation.

**Comment by bobschi** [comment]
@flozzone both of @SxDx suggestions at once would be perfect.

**Comment by flozzone** [comment]
Readme file updated, but getting celery running in vagrant isn't that easy. I will keep this open in the meantime.
